---
- name: Install Apache Tomcat 8 using ansible
  hosts: g1
  remote_user: centos
  become: true

  tasks:
  - name: Update and upgrade the yum Packages
    yum:
      name: '*'
      state: latest      
      update_cache: yes
    become: true

  - name: Install JAVA
    yum:
      name: java
      state: present

  - name: Create a Tomcat Group
    group:
      name: tomcat

  - name: Create a Tomcat User
    user:
      name: tomcat

  - name: Create a Tomcat Directory
    file:
      path: /opt/tomcat8
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes

  - name: download & unarchive tomcat8
    unarchive:
      src: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
      dest: /opt/tomcat8
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership of tomcat directory
    file:
      path: /opt/tomcat8
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
      src: tomcat.service
      dest: /etc/systemd/system/
      mode: 0755
  - name: deploying the new WAR-file to all target servers
    copy:
      src: /var/lib/jenkins/workspace/JavaCalculatorWebApp/target/webapp-0.2.war
      dest: /opt/tomcat8/webapps
      mode: 0755
      
  - name: Start and Enable Tomcat 8 on server
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
    become: true
...
